---
title: "Estado del COVID-19 en Costa Rica"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Los siguientes gráficos han sido generados a partir de los [datos publicados por el Ministerio de Salud](http://geovision.uned.ac.cr/oges/).

```{r message=FALSE}
# Carga de graphics
library(graphics)

# Carga de ggplot2
library(ggplot2)

# Carga de plotly
library(plotly)

# Carga de dplyr
library(dplyr)

# Carga de datos desde un archivo CSV
cr_covid19 <- 
  read.csv(
    file='https://raw.githubusercontent.com/gf0604-procesamientodatosgeograficos/2021i-datos/main/ministerio-salud/covid/ultimafecha_CSV_GENERAL.csv', 
    sep = ","
  )

# Conversión de la columna de fecha a la clase Date
cr_covid19$FECHA <- as.Date(cr_covid19$FECHA, "%d/%m/%Y")
```


## Evolución de los casos a través del tiempo

### plot()

```{r}
# Gráfico generado con plot()
plot(
  cr_covid19$FECHA, 
  cr_covid19$positivos,
  main='Evolución en el tiempo de los casos de COVID-19 en CR',
  xlab='Fecha',
  ylab='Casos',
  type="l",
  col="blue"
)
axis(1, cr_covid19$FECHA, format(cr_covid19$FECHA, "%d %b"), tick = FALSE)

# Casos activos
lines(cr_covid19$FECHA, cr_covid19$activos, col="red")

# Casos recuperados
lines(cr_covid19$FECHA, cr_covid19$RECUPERADOS, col="green")

# Casos fallecidos
lines(cr_covid19$FECHA, cr_covid19$fallecidos, col="violet")
```

### ggplot()
```{r}
# Gráfico generado con ggplot()
ggplot(cr_covid19, aes(x=FECHA)) + 
  ggtitle("Evolución en el tiempo de los casos de COVID-19 en CR") +
  xlab("Fecha") + 
  ylab("Casos") +
  geom_line(aes(y = positivos), color = "blue") +
  geom_point(aes(y = positivos), color = "blue") + 
  geom_line(aes(y = activos), color = "red") +
  geom_point(aes(y = activos), color = "red") +   
  geom_line(aes(y = RECUPERADOS), color="green") +
  geom_point(aes(y = RECUPERADOS), color = "green") +
  geom_line(aes(y = fallecidos), color="violet") +
  geom_point(aes(y = fallecidos), color = "violet") 
```

### plot_ly()
```{r echo=FALSE}
# Gráfico generado con plot_ly()
plot_ly(data = cr_covid19,
                x = ~ FECHA,
                y = ~ positivos, 
                name = 'Positivos', 
                type = 'scatter',
                mode = 'lines',
                line = list(color = "blue")) %>%
  add_trace(y = ~ activos,
                    name = 'Activos',
                    mode = 'lines',
                    line = list(color = "red")) %>%
  add_trace(y = ~ RECUPERADOS,
                    name = 'Recuperados',
                    mode = 'lines',
                    line = list(color = "green")) %>%
  add_trace(y = ~ fallecidos,
                    name = 'Fallecidos',
                    mode = 'lines',
                    line = list(color = "violet")) %>%  
  layout(title = "",
                 yaxis = list(title = "Cantidad de casos"),
                 xaxis = list(title = "Fecha"),
                 legend = list(x = 0.1, y = 0.9),
                 hovermode = "compare")

```


### ggplot()
#### Hecho por mi persona 
```{r }
# Gráfico generado con ggplot()
ggplot(cr_covid19, aes(x=FECHA)) + 
  ggtitle("Evolución en el tiempo de los casos de COVID-19 en CR") +
  xlab("Fecha") + 
  ylab("Casos") +
  geom_line(aes(y = positivos), color = "blue") +
  geom_point(aes(y = positivos), color = "blue") + 
  geom_line(aes(y = activos), color = "red") +
  geom_point(aes(y = activos), color = "red") +   
  geom_line(aes(y = RECUPERADOS), color="green") +
  geom_point(aes(y = RECUPERADOS), color = "green") +
  geom_line(aes(y = fallecidos), color="violet") +
  geom_point(aes(y = fallecidos), color = "violet")
```


### Plot_ly()
#### Hecho por mi persona
```{r echo=FALSE}
# Gráfico generado con plot_ly()
plot_ly(data = cr_covid19,
                x = ~ FECHA,
                y = ~ positivos, 
                name = 'Positivos', 
                type = 'scatter',
                mode = 'lines',
                line = list(color = "blue")) %>%
  add_trace(y = ~ activos,
                    name = 'Activos',
                    mode = 'lines',
                    line = list(color = "red")) %>%
  add_trace(y = ~ RECUPERADOS,
                    name = 'Recuperados',
                    mode = 'lines',
                    line = list(color = "green")) %>%
  add_trace(y = ~ fallecidos,
                    name = 'Fallecidos',
                    mode = 'lines',
                    line = list(color = "violet")) %>%  
  layout(title = "",
                 yaxis = list(title = "Cantidad de casos"),
                 xaxis = list(title = "Fecha"),
                 legend = list(x = 0.1, y = 0.9),
                 hovermode = "compare")
```
